import { Badge, ListGroup } from 'react-bootstrap';
import { BIRDS_HOST } from '../Constants';
import { formatNumber } from '../helpers/helpers';
import { useAppSelector } from '../store/Store';
import { OverviewStatsResponse } from '../types/BirdnetPi';

/**
 * Returns a ListGroup.Item that includes a name and an optional badge with a formatted numeric value.
 */
export const OverviewStatItem = (props: { name: string; value?: number }): JSX.Element => {
    return (
        <ListGroup.Item className="d-flex align-items-center justify-content-between">
            <div className="me-2 fst-italic">{props.name}:</div>
            <div>
                <Badge>{props.value ? formatNumber(props.value, 0) : '--'}</Badge>
            </div>
        </ListGroup.Item>
    );
};

/**
 * Returns the Top 10 Chart that is generated by the BirdnNET-Pi backend
 */
const Top10LastUpdateChart = (props: {
    overviewStats?: OverviewStatsResponse;
}): JSX.Element | null => {
    if (props.overviewStats) {
        const { overviewStats } = props;
        return (
            <img
                className="img-fluid img-thumbnail mt-2"
                src={`${BIRDS_HOST}/${overviewStats?.stats.chart}`}
                alt={`Detections chart for ${overviewStats?.date}`}
                aria-label={`Detections chart for ${overviewStats?.date}`}
            />
        );
    }

    return null;
};

/**
 * Stats block at the top of the homepage
 */
export const HomepageStats = (): JSX.Element => {
    const overviewStats = useAppSelector((state) => state.overviewStats.value);

    return (
        <div className="mb-3 d-flex align-items-center flex-column">
            <h5 className="text-center">Stats</h5>

            <div className="text-center">
                <ListGroup className="list-group-horizontal-md">
                    <OverviewStatItem name="Today" value={overviewStats?.stats.todaysDetections} />
                    <OverviewStatItem
                        name="Last Hour"
                        value={overviewStats?.stats.lastHourDetections}
                    />
                    <OverviewStatItem
                        name="Species Today"
                        value={overviewStats?.stats.speciesToday.length}
                    />
                    <OverviewStatItem
                        name="Species All-Time"
                        value={overviewStats?.stats.speciesAllTime.length}
                    />
                    <OverviewStatItem
                        name="Total All-Time"
                        value={overviewStats?.stats.totalDetections}
                    />
                </ListGroup>
            </div>

            <Top10LastUpdateChart overviewStats={overviewStats} />
        </div>
    );
};
